#!/bin/bash

xgettext --language=Python --keyword=_ --output=snowlinux-installer.pot usr/lib/snowlinux-installer/installer.py usr/lib/snowlinux-installer/main.py usr/lib/snowlinux-installer/frontend/gtk_interface.py
