#!/bin/bash

sudo rm -rf /etc/snowlinux-installer
sudo rm -rf /etc/init.d/snowlinux-installer
sudo rm -rf /usr/bin/snowlinux-installer
sudo rm -rf /usr/bin/snowlinux-installer-dm
sudo rm -rf /usr/lib/snowlinux-installer
sudo rm -rf /usr/share/snowlinux-installer
sudo rm -rf /usr/share/menu/snowlinux-installer
sudo rm -rf /usr/share/icons/snowlinux-installer.png
sudo rm -rf /usr/share/icons/snowlinux-installer.xpm
sudo rm -rf /usr/share/applications/snowlinux-installer-launcher.desktop
sudo rm -rf /usr/share/snowlinux-installer-slideshow

sudo cp -R usr /
sudo cp -R etc /
sudo cp -R slideshow/usr /

snowlinux-installer --debug
